### ISSUE TITLE
Cannot see window content in Windows 7

### ISSUE THREAD

**Issue by russ3ell** [fathomssen/redtimer#101]
I am using Windows 7 64 bit SP1 and whilst the default and settings windows appear, there is no content.  Does the app need something else installed before it works

**Comment by fathomssen** [comment]
Hi @russ3ell 

What do you mean by "no content"? Is the window completely grey? Or are just the entries in the fields missing?

Could you please post a screenshot?

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
Here is a screen shot

**Comment by fathomssen** [comment]
That's weird. Did you use the latest RedTimer 1.2.2 Windows binary? Which graphics card and drivers are you using? Is this in a virtual machine?

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
I have now tried it on a desktop PC and it displayed the data.  I am using a Dell Inspiron laptop and an Intel HD Graphics 3000 Driver.  The built-in monitor uses a generic PnP monitor: refresh rate: 60; TrueColor (32 bit); Resolution 1366 x 768

**Comment by fathomssen** [comment]
Hmmm... does this desktop PC also run Windows 7? As SP1 is quite outdated - have you installed all current updates?

**Comment by russ3ell** [comment]
I have now run Microsoft update on the laptop and it has all the latest updates, but the issue is the same.  The desktop was using Windows 7 with SP1 and has a very similar build to the laptop, but obviously the hardware and associated drivers are different.  Next week I will be able to try it out on some different laptops to see if it is a common problem to laptops.

I see you are working within a QT Framework.  I will try downloading the framework and see if that changes anything

Russell

**Comment by russ3ell** [comment]
I have now installed QT and it made no difference

**Comment by fathomssen** [comment]
Hi

Could you please have a look at the Qt 5.7 build at https://ci.appveyor.com/api/buildjobs/2oo5bfc60u6p4nqt/artifacts/redtimer-1.2-419-win32-qt57-installer.exe? It helped on a Linux machine where I had problems with Qt 5.8...

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
I tried that version, but it made no difference

**Comment by fathomssen** [comment]
Hi

As I do not have access to a machine with the same problem as yours, I kindly ask you to perform the following tasks and check whether RedTimer works after each step.

This requires that you have installed Qt 5.8 with MinGW from https://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-windows-x86-mingw530-5.8.0.exe. It should be installed in the default location (`C:\Qt\Qt5.8.0`).

Also, please unpack RedTimer 1.2.4 from https://github.com/fathomssen/redtimer/releases/download/v1.2.4/redtimer-v1.2.4-win32-qt58-portable.zip to some directory, e.g. in your home directory. I will call this directory `%redtimer%`.

1. Copy `C:\Qt\Qt5.8.0\5.8\mingw53_32\bin\opengl32sw.dll` to `%redtimer%`.
2. Copy `C:\Qt\Qt5.8.0\5.8\mingw53_32\bin\*.dll` (all DLL files) to `%redtimer%` (overwriting existing files).
3. Copy `C:\Qt\Qt5.8.0\5.8\mingw53_32\plugins\*` (all sub-directories) to `%redtimer%`.

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
I have tried that and it still doesn’t work

Russell Rose
Development Manager

[Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Passfield logo.jpg]<http://www.passfield.co.uk/>

01404 514400

Passfield Data Systems Ltd  VAT Registration No: 673 8387 86  Company Registration No: 3130617  Registered address: Corrie Edge House, Corry Road, Hindhead, Surrey, GU26 6PB

This email is sent in confidence for the addressee(s) only.  If you receive this communication in error, please notify us immediately and delete any copies.  Passfield Data Systems Ltd cannot accept responsibility for any loss or damage arising from any use of this e-mail or attachments. Any views expressed may not necessarily be the views of the company.  All reasonable precautions have been taken to ensure no viruses are present in this e-mail however we recommend that you subject these to your virus checking procedures prior to use.

**Comment by fathomssen** [comment]
I really don't get this. Also, Google is no help here :(

Could you please try older versions of RedTimer?

- https://github.com/fathomssen/redtimer/releases/tag/v1.1.1
- https://github.com/fathomssen/redtimer/releases/tag/v1.0.1

What about other Qt5 applications? For example https://qupzilla.com/download#windows?

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
I tried v1.1 and got the attached error.  It looks like it is something to do with the graphics drivers.  I am going to try downloading the latest OpenGL drivers for Intel and see if that sorts the problem out
![croppercapture 69](https://cloud.githubusercontent.com/assets/28350910/25754724/2f9e4d4e-31b8-11e7-8ec9-7ad16a9f2723.jpg)

**Comment by russ3ell** [comment]
I was missing the d3dcompiler_47.dll and when I copied it from QT into any of the versions then they worked correctly

**Comment by fathomssen** [comment]
Thank you very much for your help!

Could you please try the build from https://ci.appveyor.com/api/buildjobs/0po24pyiks2320c2/artifacts/redtimer-1.2-434-win32-qt58-installer.exe? I included the d3dcompiler_47.dll from Qt Creator there.

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
Sorry it has been a while to get back to you.  I tried the new version and I was able to see the setup and configure the product.  But then I was unable to pick up a list of issues.  The program had said I was connected and I could set the custom fields without a problem.  I had reverted back to Windows 7 SP1 and so I thought I should update to the latest version and try again but nothing changed.

This had worked on the desktop version.  Any suggestions?

Russell

**Comment by fathomssen** [comment]
Sorry, my bad. Should work with release 1.2.5.

Best regards
Frederick Thomssen

**Comment by russ3ell** [comment]
That worked without any issues.  Brilliant

I was wondering if it would be difficult to add a new feature to pause the timer.  Often I am working on multiple issues as I am waiting for something to happen (e.g. copying a large file).  Ideally I would like to pause the timer during this time.

All the best

Russell

**Comment by fathomssen** [comment]
Great to hear and thank you again for your help!

Could you please create a new issue for your pause request?

Best regards
Frederick Thomssen
