### ISSUE TITLE
Version 1.2.11 do not start on win 10. 

### ISSUE THREAD

**Issue by testniracun** [fathomssen/redtimer#130]
Version 1.2.11 do not start on win 10. Because of missing Qt5QmlModels.dll.
Tested installer and portable version.

**Comment by fathomssen** [comment]
Hi @testniracun 

Could you please check this build? https://ci.appveyor.com/project/fathomssen/redtimer/builds/33569170/artifacts

Cheers
Freddy

**Comment by testniracun** [comment]
I have tested install and zip. Now there is no bug and no application. But in Event Viewer I have Error logged.

For zip:
Faulting application name: redtimer.exe, version: 9999.0.0.12, time stamp: 0x5ee9beab
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x0001f9c3
Faulting process ID: 0x2718
Faulting application start time: 0x01d6448558d15d20
Faulting application path: C:\Users\User\Downloads\redtimer-branch-master-win32-portable\redtimer-branch-master-win32\redtimer.exe
Faulting module path: C:\Users\User\Downloads\redtimer-branch-master-win32-portable\redtimer-branch-master-win32\libstdc++-6.dll
Report ID: 060430a4-beaa-4722-85b3-14836f06432e
Faulting package full name: 
Faulting package-relative application ID: 

For Install:
Faulting application name: redtimer.exe, version: 9999.0.0.12, time stamp: 0x5ee9beab
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x0001f9c3
Faulting process ID: 0x2cdc
Faulting application start time: 0x01d64483cb217ae9
Faulting application path: C:\Program Files (x86)\Thomssen IT\RedTimer\redtimer.exe
Faulting module path: C:\Program Files (x86)\Thomssen IT\RedTimer\libstdc++-6.dll
Report ID: 36ae1ad4-cb82-402d-bf8e-e75eba4d1443
Faulting package full name: 
Faulting package-relative application ID: 

And for libstds++-6.dll:
Fault bucket 1903191447828822732, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: redtimer.exe
P2: 9999.0.0.12
P3: 5ee9beab
P4: libstdc++-6.dll
P5: 0.0.0.0
P6: 00000000
P7: 40000015
P8: 0001f9c3
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33DD.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER349A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34BA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34BA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34CB.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_redtimer.exe_38eb3da1eee8ced29df4018cd34e95f7aee4753_0e83347b_b8b1cc4d-8940-4975-91e6-c8a575dcda3d

Analysis symbol: 
Rechecking for solution: 0
Report Id: a0f1a0fb-646d-4c69-9332-0359256d6d00
Report Status: 268435456
Hashed bucket: db2d8e9cd422529eea697e89cb65facc
Cab Guid: 0

**Comment by fathomssen** [comment]
Hi @testniracun 

There seems to be a Problem with Qt 5.14+. I will check this some time later.

Meanwhile, please check this version https://ci.appveyor.com/project/fathomssen/redtimer/builds/33623793/artifacts

Also please check if SSL is working.

Thanks and cheers
Freddy

**Comment by testniracun** [comment]
This version installed fine, and works okay. I tested installer and zip.
I did not check, check box ignore SSL errors and it is working fine. 
But, I don't know if our redmine server uses SSL or not.
