### ISSUE TITLE
RedTimer application doesn't start

### ISSUE THREAD

**Issue by thomas694** [fathomssen/redtimer#132]
When starting the application on a system without installation of Qt5, the application doesn't start, because Qt5QmlModels.dll is missing (maybe others too).
I tested it with the current version (v1.2.11).

**Comment by fathomssen** [comment]
Hi @thomas694 

Sorry for the late reply. It seems that Qt5QmlModels.dll was not included in AppVeyor's build of Qt 5.13.2 but Qt 5.15.0 seems to include it.

Could you please try the build from [https://ci.appveyor.com/project/fathomssen/redtimer/builds/35823793/artifacts](https://ci.appveyor.com/project/fathomssen/redtimer/builds/35823793/artifacts)?

Cheers
Freddy

**Comment by thomas694** [comment]
Hi Freddy,

I have tested it with the portable version. It works now. Thanks.

It's a great app, but I've wished for something else. Actually I'm searching a way to summarize times on a handful of tickets, later I want to book the totals and not immediately when I change a ticket.

Cheers
Thomas
