### ISSUE TITLE
Windows build: TLS initialization failed

### ISSUE THREAD

**Issue by konse-github** [fathomssen/redtimer#133]
I like this great tool! However, it only works well in Linux, I did not manage to use the Windows version.

Portable version: redtimer-v1.2.12-win32
![grafik](https://user-images.githubusercontent.com/73637414/97544701-46645200-19ca-11eb-91bf-91e9f01fe4e2.png)

Redmine works well in browser without any TLS problems (internal network).
I cannot manage Redtimer to establish a connection properly (always "TLS initialization failed"):
![grafik](https://user-images.githubusercontent.com/73637414/97544937-92af9200-19ca-11eb-8918-a9ed0e899e64.png)

I also tried to use the installer version. Same problem.
Is there any Trick to get it work?

**Comment by mehmetalianil** [comment]
I have the exact same issue.
![image](https://user-images.githubusercontent.com/551129/98561459-380b1580-22a9-11eb-90ad-c21361ac4f39.png)

URL is: https://redmine4.grusbv.com

**Comment by konse-github** [comment]
I have it also at other Redmine instances. Maybe a Problem of using OpenSSL?

**Comment by mehmetalianil** [comment]
I tried the following portable versions: 

1.2.9 win32 -- did not alert me, but does not connect, therefore not functional.
1.2.10 win32 -- Qt5QmlModels.dll was not found (Also triggers antivirus, so maybe that is the reason.)
1.2.11 win32 -- Qt5QmlModels.dll was not found 
1.2.12 win32 -- same as in installer version

**Comment by mehmetalianil** [comment]
Needless to say, this is also  with Ignore SSL errors checked.

**Comment by fathomssen** [comment]
Hi guys

Sorry for the late reply. I will look into in within the next few days. As I currently don’t have a running Redmine instance: Can I use any of your URL‘s for testing?

Cheers
Freddy

**Comment by mehmetalianil** [comment]
Can arrange that, would a user with a dummy Project do?

**Comment by mehmetalianil** [comment]
I am not sure how to exchange data, we can chat here:
https://chat.grusbv.com/#/welcome
You can join #public as Guest without any bells and whistles.

**Comment by lych** [comment]
Hi, guys!
Starting from Qt 5.12.4 it needs OpenSSL 1.1.x which is binary incompatible with 1.0.x.
Whereas redtimer builds with 5.15 there are still OpenSSL 1.0.x in the setup.
Just install openssl 1.1.x or put libcrypto-1_1-x64.dll and libssl-1_1-x64.dll into redtimer.exe folder. It will start working.

**Comment by fathomssen** [comment]
Oh thank you so very much! Where can I fetch those OpenSSL libs to pack it into the installer?

**Comment by lych** [comment]
I've downloaded here: https://mirror.firedaemon.com/OpenSSL/openssl-1.1.1i-dev.zip

**Comment by fathomssen** [comment]
Hi guys, could you please try this build? https://ci.appveyor.com/project/fathomssen/redtimer/builds/36513374/artifacts

**Comment by lych** [comment]
I've tried the new portable version, works well. Thanks for fixing.

**Comment by fathomssen** [comment]
Thank you very much for your help! If everything goes smooth, new packages can soon be found here: https://github.com/fathomssen/redtimer/releases/tag/v1.2.13
