### ISSUE TITLE
El-Capitan visual glitches

### ISSUE THREAD

**Issue by yarons** [fathomssen/redtimer#17]
Latest binary (redtimer-v1.1.0-osx-10.11-el-capitan.dmg)
Almost unusable.
Resizing doesn't change a thing.

![screen shot 2016-05-25 at 11 25 43](https://cloud.githubusercontent.com/assets/406826/15533057/72135636-226b-11e6-9be1-0b2256a71dc5.png)

**Comment by fathomssen** [comment]
Hi yarons

Thanks for your feedback. As I am no OS X user myself, I require some assistance from you.

- What do you mean by "Resizing doesn't change a thing"? Doesn't the windows resize at all? Or does the window resize but the content (i.e. those tabs and checkboxes) does not move?

- Do you experience the same problems with other windows as well? Does it work in the main window or in the issue creator?

Best regards
Frederick Thomssen

**Comment by yarons** [comment]
That's what I meant:
![screen shot 2016-05-25 at 11 36 14](https://cloud.githubusercontent.com/assets/406826/15533338/ec2bc74a-226c-11e6-9262-db75adc80356.png)

I don't really know how to click but the first prompt asking me for a project name works.

**Comment by fathomssen** [comment]
Can you please check the OS X build for version 1.1.1?

https://github.com/fathomssen/redtimer/releases/tag/v1.1.1

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Had to remove the build, will come back later.

**Comment by yarons** [comment]
Checked again, here are the results:
<img width="732" alt="screen shot 2016-05-25 at 18 39 32" src="https://cloud.githubusercontent.com/assets/406826/15546372/549c3e32-22a8-11e6-888c-abaaadb70053.png">

**Comment by fathomssen** [comment]
OK, but can you resize the Settings window now properly?

**Comment by yarons** [comment]
I can but this is the initial state and the items are still aligned along the border with no spacing.

**Comment by fathomssen** [comment]
Yep, it's not pretty but at least you now can work with it :)

I had some platform-dependent issues with resizing before and will most hopefully resolve this one, too. Have you got any experience with QML?

The same goes for the missing borders on settings, issue creator and issue selector. Still figuring it out.

**Comment by fathomssen** [comment]
Hi

Does the situation improve on https://github.com/fathomssen/redtimer/releases/tag/v1.1-gui1?

Best regards 
Frederick Thomssen

**Comment by yarons** [comment]
I know a guy, I'll try and see if he's available.

I'm not sure it's completely perfect but it looks better.
<img width="690" alt="screen shot 2016-05-27 at 11 10 01" src="https://cloud.githubusercontent.com/assets/406826/15602047/99d2e47a-23fb-11e6-9b9b-5c7f194ca949.png">

**Comment by fathomssen** [comment]
Well, that certainly looks better. Although the icons are too small as I have seen on a colleague's Macbook before.

In the settings windows, does the first row ("Profile...") move out from under the tabs when you increase the window's size?

**Comment by yarons** [comment]
At some point yes.
<img width="427" alt="screen shot 2016-05-27 at 11 44 42" src="https://cloud.githubusercontent.com/assets/406826/15602912/75c3d3dc-2400-11e6-9dfb-bf7b88b16ed9.png">

**Comment by yarons** [comment]
The icon should be of better quality, it looks like a poor assembly of red pixels :)

**Comment by fathomssen** [comment]
When you compile RedTimer on OS X yourself, the icons are all fine. It's just a problem with OS X on Travis CI. Maybe I have to add another switch... I will ask the Internet!

**Comment by fathomssen** [comment]
Hi

Could you please check whether this version looks better?

https://github.com/fathomssen/redtimer/releases/tag/v1.1-gui3

If it does not improve anything, could you please try to set the environment variable `QT_SCALE_FACTOR=2` before starting RedTimer? E.g. `QT_SCALE_FACTOR=2 ./RedTimer`.

Best regards
Frederick Thomssen

**Comment by yarons** [comment]
This is with the QT_SCALE_FACTOR variable (It's as big as it looks):
![screen shot 2016-05-29 at 13 27 36](https://cloud.githubusercontent.com/assets/406826/15632609/32d15b56-25a1-11e6-8bf8-267b78cdc4ef.png)

**Comment by fathomssen** [comment]
And without the variable, nothing changed?!

**Comment by yarons** [comment]
Exactly the same scale.

**Comment by fathomssen** [comment]
Hi @yarons

This version now considers the device pixel ratio (which is 2x for Retina displays) for window sizes:

https://github.com/fathomssen/redtimer/releases/download/v1.1-gui4/redtimer-v1.1-gui4-osx-10.11-el-capitan.dmg

Could you please check that one?

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Fixed with test version: https://github.com/fathomssen/redtimer/releases/tag/deploy2

**Comment by fathomssen** [comment]
Hi @yarons 

RedTimer works pretty well now on OS X. If you've got time to test it, please use the current pre-release: https://github.com/fathomssen/redtimer/releases

Best regards
Frederick Thomssen
