### ISSUE TITLE
Windows 10 on Parallels visual glitches

### ISSUE THREAD

**Issue by yarons** [fathomssen/redtimer#19]
I'm having a productive day today :)

This happens right after I've entered the project name:
![capture1](https://cloud.githubusercontent.com/assets/406826/15533695/7df001b8-226e-11e6-9c78-ce5e8154ba72.PNG)

![capture2](https://cloud.githubusercontent.com/assets/406826/15533721/93e1aac6-226e-11e6-8450-988697f184cb.PNG)

**Comment by fathomssen** [comment]
Huh! I am developing and testing it on Windows 10 as well and did not experience any such issues. Could you please give me some more information about your machine? Is it a virtual machine? Which graphics card do you use?

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Could you please check version 1.1.1?

https://github.com/fathomssen/redtimer/releases/tag/v1.1.1

Best regards
Frederick Thomssen

**Comment by yarons** [comment]
Slightly better.
![capture3](https://cloud.githubusercontent.com/assets/406826/15537474/543ff6be-227f-11e6-9b71-5c7f55591c04.PNG)

**Comment by fathomssen** [comment]
Did you build it yourself or did you use my binary?

**Comment by yarons** [comment]
Yours.

**Comment by fathomssen** [comment]
Is that the initial size for the main window after you started RedTimer?

**Comment by fathomssen** [comment]
Hi

Can you please test the version on https://github.com/fathomssen/redtimer/releases/tag/v1.1-gui1?

Best regards
Frederick Thomssen

**Comment by yarons** [comment]
There you go (GUI Test 2)
<img width="399" alt="screen shot 2016-05-27 at 11 00 45" src="https://cloud.githubusercontent.com/assets/406826/15601836/6668adfa-23fa-11e6-8044-0063d806d116.png">

**Comment by fathomssen** [comment]
I honestly have to say that I don't get it. What is your screen resolution and your DPI settings? Does resizing the settings window now work properly?

**Comment by yarons** [comment]
Resizing does, I'm using Win10 w/ Parallels on 15" Retina Mac.

**Comment by fathomssen** [comment]
Aaah, that is why I asked you earlier about your machine :)

I will try to find out why this behaves differently on Win10/Parallels. But I cannot promise anything. This is not quite the most usual scenario, of course.

**Comment by fathomssen** [comment]
Hi

Could you please check whether this version looks better?

https://github.com/fathomssen/redtimer/releases/tag/v1.1-gui3

Best regards
Frederick Thomssen

**Comment by yarons** [comment]
Nope.
![screen shot 2016-05-29 at 13 30 40](https://cloud.githubusercontent.com/assets/406826/15632632/9249ddc4-25a1-11e6-8519-3af26f064ffd.png)

**Comment by fathomssen** [comment]
Hi @yarons 

This version now considers the device pixel ratio (which is 2x for Retina displays) for window sizes: https://github.com/fathomssen/redtimer/releases/download/v1.1-gui4/redtimer-v1.1-gui4-win32.zip

Could you please check that one?

Best regards
Frederick Thomssen

**Comment by yarons** [comment]
![screen shot 2016-06-02 at 17 40 58](https://cloud.githubusercontent.com/assets/406826/15748944/51019960-28e9-11e6-9f33-b17a32842cf2.png)

**Comment by fathomssen** [comment]
Could you check the OSX one in issue #17 as well, please?
