### ISSUE TITLE
Process does not terminate on closing the main window

### ISSUE THREAD

**Issue by janhicken** [fathomssen/redtimer#32]
When the main window has been closed, the RedTimer process doesn't terminate. I have to kill it using Ctrl+C or using the tray icon each time. 

Could you supply an option to terminate the program in the main window?

**Comment by fathomssen** [comment]
I will enhance RedTimer by an option that switches the close button behaviour to either minimise the program to the systray or to close the program.

**Comment by fathomssen** [comment]
Fixed with commit 6079bb9.
