### ISSUE TITLE
Setup a Demo of Redtimer

### ISSUE THREAD

**Issue by GChester** [fathomssen/redtimer#56]
This seems like exactly what we need but it was hard to determine without any for of demo or visual guide.

With all the bad plugins on the Redmine Plugin directory sorting thru to find the good ones is difficult.

**Comment by fathomssen** [comment]
Would you suggest some screenshots of the main window, the issue creator etc. as a image slide?

**Comment by fathomssen** [comment]
Added screenshots with commits 5d74936fd442531f2e83247506e551c9796a8823 and ff8dc3040ec4d303ef2eaea0fe9071e8b37c2f96

**Comment by fathomssen** [comment]
The screenshots were taken with the pre-release version https://github.com/fathomssen/redtimer/releases/tag/v1.2-pre2.

Best regards
Frederick Thomssen
