### ISSUE TITLE
Supporting modern TLS-Configuration

### ISSUE THREAD

**Issue by c-eller** [fathomssen/redtimer#93]
As far as i can see, red timer does not support TLS1.2-Connections and/or connections with AES256-only ciphersuites. 

Any chance of using a newer TLS-Library (QT5.7)?

**Comment by fathomssen** [comment]
Hi @c-eller 

I am actually no expert in the HTTPS protocol and the different TLS versions. What exactly is your problem? Can you give me an example where connecting to a server does not work?

The releases are already compiled with Qt 5.7.

Best regards
Frederick Thomssen

**Comment by c-eller** [comment]
Hi,

thank you for your response. The redmine-instance is running behind an neins with a TLS 1.2-Configuration (comparable to the configuration "modern" you can generate with the mozilla SSLConfig-generator). The Client failed to connect until i switched TLS1.0 back on and used some older ciphers. Trying only one solution (TLS1.0 OR older ciphers) didn't help, so i strongly assume the TLS-Library doesn't support state of the art transport encryption.

Best regards

**Comment by fathomssen** [comment]
Hi @c-eller 

which OS are you using? Are you using one of my binaries? Which version?

Best regards
Frederick Thomssen

**Comment by c-eller** [comment]
Hi @fathomssen 

im using Windows 8.1 with the latest patches. I tried redtimer-v1.2-win32.zip and redtimer-v1.2.1-pre6-win32.zip releases :)

Best regeards

**Comment by fathomssen** [comment]
Hi @c-eller 

Both versions are using Qt 5.7. Do you have a Qt development environment installed in your Windows installation so you could try to compile RedTimer yourself?

I myself use AppVeyor as build service. They currently support Qt 5.7.1 (does this make a difference compared to Qt 5.7.0?) and OpenSSL 1.0.2j.

Best regards
Frederick Thomssen

**Comment by c-eller** [comment]
Hi,

i have no development Environment for compiling RedTimer. But i tried recompiling with AppVeyor; this didn't fix the issue.

Thank you,

Christopher

**Comment by fathomssen** [comment]
Hi @c-eller 

Does this work with the lastest release? https://github.com/fathomssen/redtimer/releases/tag/v1.2.4

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Please rather try https://github.com/fathomssen/redtimer/releases/tag/v1.2.5

**Comment by c-eller** [comment]
Works with 1.2.5 :-)!
