### ISSUE TITLE
Add a comment field that will be saved with the time entry

### ISSUE THREAD

**Issue by GremL1N** [fathomssen/redtimer#95]
It would be usefull if there was option to enable adding comment on time save.
I mean then i stop timer i want to add comment before it save.

**Comment by fathomssen** [comment]
Hi @GremL1N 

Thanks for your suggestion. I will add this field in a coming release.

Best regards
Frederick Thomssen

**Comment by GremL1N** [comment]
if there is a comment, a pause will be necessary.
For example: 
1 start timer 
2 do some atomic task in issue, don't finish 
3 but need to go somewhere. 
I don't want to stop timer, add comment and time entity, because when i come back i continue this issue and task. When I'm done task I'll have two time entity with same comment in issue.

**Comment by fathomssen** [comment]
Hi @GremL1N 

I already thought about splitting the start/stop button into a start/pause button and a save button. This way, you can either pause the current time tracking and then save the time or directly save the time.

In that case, another option in the configuration is needed to enable users to revert to the current behaviour (which probably most will want).

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Btw, already suggested in issue #24. So closing this one.

Best regards
Frederick Thomssen
